CREATE DATABASE customer_behaviour;
USE customer_behaviour;
show tables;

select * from customer;

-- what is the total revenue generated by male and female?
select gender, sum(purchase_amount) as "Total_Revenue" from customer
group by gender;

-- which customer use discount but still spend more than average purchase amount?
select * from customer
where discount_applied = "yes" and purchase_amount >= (select avg(purchase_amount) from customer);

-- Which are the top 5 product with the highest average review rating
select item_purchased as Product, avg(review_rating) as "Average_Review" from customer
group by item_purchased
order by Average_Review desc
limit 5;

-- Compare the average purchase amount between standard and express shipping?
select shipping_type, avg(purchase_amount) as "Average_Amount" from customer
where shipping_type in ("Express", "Standard")
group by shipping_type;

-- Do subscribed customer spend more? compare average spend and total revenue 
-- between subscribers and non subscribers?
select subscription_status ,count(customer_id) as "Total_customer",avg(purchase_amount) as "Average_spend", sum(purchase_amount) as "total_revenue" from customer
group by subscription_status
order by total_revenue, Average_spend desc;

-- Which 5 product have highest percentage of purchase with discount applied?
select item_purchased,
round(100 * sum(case when discount_applied = "yes" then 1 else 0 end )/count(*), 2) as "Discount_rate"
from customer
group by item_purchased
order by Discount_rate desc
limit 5;

-- Segment customer into new , return or loyal based on their previous purchase
-- and count the number of each segemt?
with customer_type as(
select customer_id, previous_purchases ,
case
    when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "returning"
    else "Loyal"
    end as customer_segment
from customer    
)
select customer_segment , count(*) as "number of customer"
from customer_type
group by customer_segment;

-- What are the top 3 most purchased product within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as "Total_Revenue"from customer
group by age_group
order by Total_Revenue desc;

